# Generated by Django 5.2.10 on 2026-01-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_registrationfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationfee',
            name='image_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
