# Generated by Django 5.2.10 on 2026-01-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_thrifts_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
