# Generated by Django 5.2.10 on 2026-01-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_purchase_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thrifts',
            name='thriftquantity',
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
