# Generated by Django 5.2.10 on 2026-01-23 00:58

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_thrifts_thriftquantity_purchase_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.get_package_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.purchase')),
            ],
        ),
    ]
