# Generated by Django 5.2.10 on 2026-02-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_packageimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='thrift',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thrifts',
            name='thriftdescription',
        ),
        migrations.RemoveField(
            model_name='thrifts',
            name='thriftprice',
        ),
        migrations.DeleteModel(
            name='PackageImage',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
