# Generated by Django 5.2.10 on 2026-03-04 08:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_userpurchase_status_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='registrationfee',
            name='image_upload',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
